[project]
name = "dataset-qm9-preprocessed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.0",
    "pytest>=8.3.4",
    "requests>=2.32.3",
    "torch>=2.5.1",
]
